language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -U tox
  - pip install python-coveralls
script:
  - tox -r
after_success:
  - coveralls

notifications:
  email: false

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
